### ISSUE TITLE
Rocko branch bbappends wrong version

### ISSUE THREAD

**Issue by dl9pf** [Linaro/meta-qcom#75]
You bbappend gpsd-3.17 whereas http://git.openembedded.org/meta-openembedded/tree/meta-oe/recipes-navigation/gpsd?h=rocko&id=352531015014d1957d6444d114f4451e241c4d23 has 3.16 . 

Error: 
Parsing recipes: 100% |################################################################################################################################################################| Time: 0:00:57
Parsing of 2367 .bb files complete (0 cached, 2367 parsed). 3262 targets, 297 skipped, 0 masked, 0 errors.
ERROR: No recipes available for:                                                                                                                                                                     
  /build-master2/meta-qcom/openembedded-layer/recipes-navigation/gpsd/gpsd_3.17.bbappend

**Comment by ndechesne** [comment]
tl;tr
i think it should be fixed now. 

I often use meta-qcom along the side with meta-backports which we maintain on git.linaro.org. We bring a bunch of 'newer' recipes in meta-backports that we need for our builds, and we brought gpsd 3.17 there (for rocko). I have now added a mechanism to let me add patches in meta-qcom that are used/applied only when meta-backports is part of the build.

thanks for reporting this issue.

**Comment by lumag** [comment]
rocko is no longer supported
