### ISSUE TITLE
thud branch ath10k fix does not build properly with yocto

### ISSUE THREAD

**Issue by bbrother** [Linaro/meta-qcom#95]
The ath10k fix from pull request #93 breaks my build with yocto. It seems like the arch specific pre install function messes up the noarch linux-firmware recipe.  I get the follwing bitbake error:
```
No match for argument: linux-firmware-ath10k
Error: Unable to find a match
```

**Comment by ndechesne** [comment]
ouch. @alimon can you please check? let me know if you think we should revert..

**Comment by bbrother** [comment]
Note, I had to force it to try to install ath10k the MACHINE_ESSENTIAL_EXTRA_RRECOMMENDS inclusion of it failed quietly and I only noticed by looking at the rootfs manifest that it was missing.

It does work if I remove dragonboard-820c_ from the do_install_prepend function.

**Comment by lumag** [comment]
The thud branch is no longer supported.
